### PR TITLE
Removed boostrap classes

### PR DESCRIPTION
**Pull request by ibonkonesa**
Removed boostrap classes

### CODE REVIEW

**Comment by eerison** [comment]
@ibonkonesa why are you closing and opening a new PR? :confused:

**Comment by ibonkonesa** [comment]
I don't know, other people told me the same. My excuse it's that it's my first day and I finally understood that new commits are automatically added to the original PR. Sorry by the inconvenients

**Comment by eerison** [comment]
I guess you need to create a new branch ... you're committing in master ...

create a new branch from master `git checkout -b feature/remove-bootstrap-from-error-pages`

**Comment by eerison** [comment]
#295 #290

**Comment by ibonkonesa** [comment]
As I told you, I never collaborated  with other repositories using the Fork > PR flow.  Should I create a new PR from my new feature branch ? pointing to what branch? I'm really sorry if I make you lose your time

**Comment by eerison** [comment]
Hi @ibonkonesa no worries it's completely fine :)

After you create your branch, you will do a push for your respiratory, after that you'll see a button to open a Pull request , and probably the target is my master, if it's not Master you select it :)


Will be

My repository: master <- your repository: your new branch

**Comment by eerison** [comment]
If you don't understand please let me know

I'll try to explain another way 😊

**Comment by eerison** [comment]
This pull request was moved to #297

**Pull request closed without merging**
