### PR TITLE
created page style new password

### PR DESCRIPTION
**Pull request by moisesgui**
done!

### CODE REVIEW

**Comment by eerison** [comment]
Screenshot from 2020-01-08 21-32-15
 Hey @moisesgui It isn't working could you check it?

Thanks!

**Comment by moisesgui** [comment]
oks!

**Comment by moisesgui** [comment]
done! thats ok!

**Comment by eerison** [comment]
@moisesgui I'm going to merge you PR but you need to fix when the user put something wrong.
Screenshot from 2020-01-09 08-51-47


It's an example how it's working into admin page

Screenshot from 2020-01-09 08-55-15

**Pull request merged**
