### PR TITLE
added mobile classes to 404 page

### PR DESCRIPTION
**Pull request by sourcefactory-at**
Regarding issue #153 I updated the bootstrap classes on 404 page.

image

### CODE REVIEW

**Comment by eerison** [comment]
Cool, Thanks @sourcefactory-at for you fix :) 

I'm merging this PR, But I'm changing bootstrap to [bulma.io](https://bulma.io/), What do you think open a new MR removing bootstrap from error page and adding bulma? do you think it's possible? 

and other page that I really would like to change is [login](https://myprofile.pro/en/login) page, I would like to create a new one similar [register](https://myprofile.pro/en/register) page.

**Comment by eerison** [comment]
Hi @sourcefactory-at it's the issue #270 that I mentioned above :smiley:

**Comment by sourcefactory-at** [comment]
Hi @eerison, I don't think that'd be a problem and will have a look it at.

**Comment by eerison** [comment]
@sourcefactory-at please drop a message there #270 or #271 or [layout issues](https://github.com/eerison/myprofile/issues?q=is%3Aissue+is%3Aopen+label%3Alayout)

**Comment by eerison** [comment]
@sourcefactory-at could you check task #271 or other tagged as layout, because issue #270 is WIP

**Pull request merged**
